OpenShopChannel/Apps

contents/rumbler.oscmeta
I just wrote this and thought I'd submit it to OSC.
Does what it says on the tin - it makes your Wii Remote rumble.
=> Add the Rumbler app

contents/rumbler.oscmeta, contents/wiistatic.oscmeta
git felt like being funny so this PR has 3 more commits than it should, apologies for that
=> add Wii Static app

contents/ARCME.oscmeta
---
Any Region Changer: ModMii Edition, a tool used for region changing the Wii console with ModMii software. What else should I say? lol
=> Any Region Changer: ModMii Edition

contents/ARCME.oscmeta, contents/RealWnD_Mini.oscmeta, contents/SimpleIOSPatcher_Mini.oscmeta, contents/Wii_Mini_Ethernet_Enable.oscmeta
---
Those apps are specifically made for Wii mini. For more question, you can ask @playerjmr
=> Added 3 Homebrew apps for Wii mini

contents/MyMenuifyMod.oscmeta, contents/priiloader.oscmeta
The app was in emulators and not utilities.
=> Fix MyMenuifyMod category

contents/libreshop.oscmeta
---
The zip file url is hard coded because the app's hosted on an external repo and if the app is updated this will have to be modified
=> Add the LibreShop

contents/genplus-gx.oscmeta
=> fix genplus-gx.oscmeta

contents/cavex.oscmeta
>> The other open PR contains changes unrelated to CavEx
---
Update CavEX to v0.3.0-alpha per https://github.com/xtreme8000/CavEX
=> Update CavEX to v0.3.0-alpha

contents/Shiggii.oscmeta
=> Hopefully fix Shiggii

contents/wii-screen.oscmeta
---
This is an utility to try different video modes, with the possibility of adjusting parameters such as the EFB, XFB and VI sizes.
=> Add wii-screen

contents/VVVVVV.oscmeta
---
My Wii port of an entertaining 2D platform game: https://thelettervsixtim.es/
=> Add VVVVVV

contents/OceanPop.oscmeta
---
OceanPop port to the Wii: https://sharkwouter.github.io/oceanpop/
=> Add OceanPop

contents/CookwiiClicker.oscmeta
Added:
- Sound Effects
- [Y] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [Y] Have you verified that the manifest contains valid JSON?
- [Y] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [Y] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?
Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be …
=> Update to version 0.0.2

contents/schismtracker.oscmeta
---
Update from `20220125` to `20240409` bringing e.g. SDL 1.2 to SDL2, playback bugfixes, etc.
=> update Schism Tracker to 20240409

contents/crack-attack.oscmeta
=> Add Crack Attack! game

contents/mame4wii.oscmeta
=> Add mame4wii

contents/Liichess.oscmeta
---
It's a lichess.org client for the Wii using their API. @Artuto @GabubuAvailable @emilydaemon
=> Add Liichess

contents/gl-117.oscmeta
=> Add GL-117 game

contents/GRRLIB-Examples-Collection.oscmeta
=> Add GRRLIB Examples Collection

contents/WiiLink WFC Patcher.oscmeta
---
This is the Wiilink WFC Disc Patcher. I had permission from mkwcat to add this to OSC
=> Add Wiilink WFC Patcher

contents/csm-installer.oscmeta
=> Rename csm-installer repo

contents/brainslug.oscmeta
---
No more hosting the file myself, this repository was very hidden. Not even the Wiimmfi website points to this repository. This should also be more updated than the one currently hosted as well
=> found actual repository for brainslug.oscmeta

contents/ClassiCube.oscmeta, contents/linktag-app.oscmeta
---
i don't know why it has the linktag-app commit as well. just squash it and it should be fine...hopefully
=> Add ClassiCube Wii Port

contents/ntp.oscmeta, contents/sntp.oscmeta
=> Update Supported platforms for SNTP and NTP Client

contents/cheat-manager.oscmeta, contents/newobit.oscmeta
---
Newo Bit is a puzzle game created by [Owen](https://owensoft.net/project/newogame/) in which you place planets in orbit.
Cheat Manager is a utility that allows you to write, edit, and manage cheat code text files and even convert them to a usable GCT format for your games directly from the Wii console.
=> Add Newo Bit and Cheat Manager

contents/BlockamokRemix.oscmeta
---
Fly through a 3D world of never-ending blocks and survive for as long as you can! Includes customization options for both gameplay and visuals, along with five music tracks.
=> Add Blockamok Remix

contents/neverball.oscmeta
---
Wii port, using opengx. There are occasional small slowdowns, but it's playable. Video: https://vk.com/video/@daesu?z=video7200355_456239310%2Fpl_7200355_-2
=> Add Neverball

contents/WiiUnShoplifter.oscmeta
---
Adds WiiUnShoplifter, an application that removes tickets on the NAND without corresponding TMDs, useful for reverting the effects of the Wii Shoplift Channel.
=> Add WiiUnShoplifter

contents/chromono.oscmeta
---
Nice little game from Thomas Perl (https://thp.io/2013/chromono/). This is the first OpenGL 3.0 ported to the Wii using opengx.
=> Add chro.mono

contents/DiscDriveDateChecker.oscmeta
Just updating the username since I changed my github username.
=> DiscDriveDateChecker Aeplexi -> Aeplet GitHub Username Update

contents/BlockamokRemix.oscmeta, contents/Trogdor-RB.oscmeta
---
**Blockamok Remix**
- Fixed file path to follow new naming scheme
**Trogdor: Reburninated**
- Fixed author name to match the creator's current username
- Added missing peripherals
=> Trogdor: Reburninated and Blockamok Remix fixes

contents/ParentalControlsRemover.oscmeta
- [Yes] Have you checked that there aren't other open pull requests for the same manifest update/change?
- [ Yes] Have you verified that the manifest contains valid JSON?
- [ Yes] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
- [Yes ] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?
Note: *filename*.oscmeta is the **slug** of the application you are submitting. This slug is used to locate files such as "/apps/**slug**/boot.dol" and "/apps/**slug**/meta.xml" in the final archive generated by this manifest. These files should be available at this …
=> Add Parental Controls Remover

contents/TestMiiInternet.oscmeta
-[x] Have you checked that there aren't other open pull requests for the same manifest update/change?
-[x] Have you verified that the manifest contains valid JSON?
-[x] Are you certain that this manifest is not designed to obtain copyrighted material or software, which you do not have permission to distribute?
-[x] Submitting malicious software is strictly forbidden, and potentially constitutes criminal activity, punishable by law. To the best of your knowledge, is this submission clear of any malicious intent?
--- …
=> Adding TestMiiInternet

contents/scratch-wii.oscmeta
=> chore(scratch-wii): update repo url

contents/sntp.oscmeta
=> update sntp to 1.3.1
